name: CI test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
# Service containers to run with `container-job`
    services:
      # Label used to access the service container
      mongo:
        # Docker Hub image
        image: mongo
        ports:
          - 27017:27017
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        env:
          MONGODB_URL: 'mongodb://localhost:27017/photo-wall?authMechanism=DEFAULT&authSource=admin'
        run: |
          npm install
          npm run test 